-- MySQL Script generated by MySQL Workbench
-- Sex 27 Out 2017 15:56:28 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema amphora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amphora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amphora` DEFAULT CHARACTER SET utf8 ;
USE `amphora` ;

-- -----------------------------------------------------
-- Table `amphora`.`almoxarifado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amphora`.`almoxarifado` (
  `idAlmoxarifado` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlmoxarifado`))
ENGINE = InnoDB
COMMENT = 'Melhor tabela do universo';


-- -----------------------------------------------------
-- Table `amphora`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amphora`.`item` (
  `idalmoxarifado` INT NOT NULL,
  `iditem` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `info` VARCHAR(1024) NULL,
  PRIMARY KEY (`iditem`),
  INDEX `fk_item_almoxarifado1_idx` (`idalmoxarifado` ASC),
  CONSTRAINT `fk_item_almoxarifado1`
    FOREIGN KEY (`idalmoxarifado`)
    REFERENCES `amphora`.`almoxarifado` (`idAlmoxarifado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amphora`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amphora`.`usuario` (
  `idalmoxarifado` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `admin` TINYINT NOT NULL,
  `matricula` INT NULL,
  `departamento` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(16) NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_almoxarifado1_idx` (`idalmoxarifado` ASC),
  CONSTRAINT `fk_usuario_almoxarifado1`
    FOREIGN KEY (`idalmoxarifado`)
    REFERENCES `amphora`.`almoxarifado` (`idAlmoxarifado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amphora`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amphora`.`transacao` (
  `idtransacao` INT NOT NULL,
  `idusuario` INT NULL,
  `iditem` INT NULL,
  `data_solicitada` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `quantidade_entregue` INT NULL,
  `entregue?` VARCHAR(1) NULL,
  `quantidade_devolvida` INT NULL,
  `devolvida?` VARCHAR(45) NULL,
  `data_devolvida` DATETIME NULL,
  PRIMARY KEY (`idtransacao`),
  INDEX `fk_transacao_item_idx` (`iditem` ASC),
  INDEX `fk_transacao_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_transacao_item`
    FOREIGN KEY (`iditem`)
    REFERENCES `amphora`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `amphora`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
